name: Test Suite

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  tests:
    env:
      ANAPLAN_SDK_TEST_WORKSPACE_ID: ${{secrets.ANAPLAN_SDK_TEST_WORKSPACE_ID}}
      ANAPLAN_SDK_TEST_MODEL_ID: ${{secrets.ANAPLAN_SDK_TEST_MODEL_ID}}
      ANAPLAN_SDK_TEST_CERT: ${{secrets.ANAPLAN_SDK_TEST_CERT}}
      ANAPLAN_SDK_TEST_PK: ${{secrets.ANAPLAN_SDK_TEST_PK}}
      AZ_STORAGE_ACCOUNT: ${{secrets.AZ_STORAGE_ACCOUNT}}
      AZ_STORAGE_SAS_TOKEN: ${{secrets.AZ_STORAGE_SAS_TOKEN}}

    name: "Python ${{ matrix.python-version }}"
    runs-on: "ubuntu-latest"

    strategy:
      max-parallel: 4
      matrix:
        python-version: [ "3.10.4", "3.11", "3.12", "3.13" ]

    steps:
      - uses: "actions/checkout@v4"
      - uses: "actions/setup-python@v5"
        with:
          python-version: "${{ matrix.python-version }}"
      - name: "Setup"
        run: |
          pip install uv
          uv sync
      - name: "Run tests"
        run: "uv run python -m pytest -n 12 --dist loadfile tests/"
