name: Test Suite

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    env:
      ANAPLAN_SDK_TEST_WORKSPACE_ID: ${{secrets.ANAPLAN_SDK_TEST_WORKSPACE_ID}}
      ANAPLAN_SDK_TEST_MODEL_ID: ${{secrets.ANAPLAN_SDK_TEST_MODEL_ID}}
      ANAPLAN_SDK_TEST_CERT: ${{secrets.ANAPLAN_SDK_TEST_CERT}}
      ANAPLAN_SDK_TEST_PK: ${{secrets.ANAPLAN_SDK_TEST_PK}}
      AZ_STORAGE_ACCOUNT: ${{secrets.AZ_STORAGE_ACCOUNT}}
      AZ_STORAGE_SAS_TOKEN: ${{secrets.AZ_STORAGE_SAS_TOKEN}}

    name: Python ${{ matrix.python-version }}

    strategy:
      max-parallel: 4
      matrix:
        python-version: [ 3.10.4, 3.11, 3.12, 3.13 ]

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
      - name: Setup
        run: |
          uv python install ${{ matrix.python-version }}
          uv sync --dev
      - name: Tests
        run: uv run python -m pytest -n 15 --dist loadfile tests/
